---
- name: Install Chocolatey
  chocolatey.chocolatey.win_chocolatey:
    name:
      - chocolatey
      - chocolatey-core.extension
    state: present
- name: Install Chocolatey Tools
  chocolatey.chocolatey.win_chocolatey:
    name:
      - apimonitor
      - processhacker
      - pebear
      - x64dbg.portable
      - ghidra
      - cutter
      - PeStudio
      - fakenet
      - microsoft-windows-terminal
      - sysinternals
      - 7zip
      - Wireshark
      - die
      - imhex
      - explorersuite
    state: present
- name: Make Tools Dir
  ansible.windows.win_file:
    path: C:\Users\{{ ansible_user }}\Tools
    state: directory
- name: Download Zimmerman's Tools
  ansible.windows.win_powershell:
    chdir: C:\Users\{{ ansible_user }}\Tools
    creates: gz.zip
    script: |
      iwr -UseBasicParsing -Uri https://f001.backblazeb2.com/file/EricZimmermanTools/Get-ZimmermanTools.zip -OutFile gz.zip
- name: Unzip Zimmerman's Tools
  community.windows.win_unzip:
    src: C:\Users\{{ ansible_user }}\Tools\gz.zip
    dest: C:\Users\{{ ansible_user }}\Tools\gz
    creates: C:\Users\{{ ansible_user }}\Tools\gz
- name: Write Fixed Scipt
  ansible.windows.win_powershell:
    script: |
      $c = Get-Content -Path Get-ZimmermanTools.ps1
      $c -Replace 'if \(\$TestColor -eq -1\)','if ($TestColor -eq -1 -or $null -eq $TestColor )' > Get-ZimmermanTools_fixed.ps1
    chdir: C:\Users\{{ ansible_user }}\Tools\gz
    creates: C:\Users\{{ ansible_user }}\Tools\gz\Get-ZimmermanTools_fixed.ps1
- name: Get Zim Tools
  ansible.windows.win_powershell:
    chdir: C:\Users\{{ ansible_user }}\Tools\gz
    script: .\Get-ZimmermanTools_fixed.ps1
    arguments:
      - -ExecutionPolicy
      - Bypass
    executable: powershell.exe
    parameters: 
      Dest: C:\Users\{{ ansible_user }}\Tools
- name: Add Choco/Tools to path
  ansible.windows.win_path:
    elements:
      - C:\ProgramData\chocolatey\bin
      - C:\Users\{{ ansible_user }}\Tools\gz
      - C:\Users\{{ ansible_user }}\Tools\gz\net6
    state: present
    scope: user
# - name: Enable WMI tracing
#   ansible.windows.win_cmd: Wevtutil.exe sl Microsoft-Windows-WMI-Activity/Trace /e:true /q
