---
- name: Install ELK Stack
  hosts: hades-siem
  vars_prompt:
    - name: siem_password
      prompt: SIEM password
      private: false
  roles:
    - role: docker
      become: true
      become_user: root
    - elk-docker
